name: ci

on:
  push:
    branches: master

jobs:

    build-busybox:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: build
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            path: ./
            dockerfile: ./Dockerfile
            registry: docker.io
            repository: pilgrim2go/busybox
            tags: latest
        - name: testtest
          run: |
            IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

            # Change all uppercase to lowercase
            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

            # Strip git ref prefix from version
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

            # Strip "v" prefix from tag name
            [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

            # Use Docker `latest` tag convention
            [ "$VERSION" == "master" ] && VERSION=latest

            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
        -
          name: Image digest
          run: echo ${{ steps.testtest.outputs }}
        - name: Webhook
          uses: joelwmale/webhook-action@master
          with:
            url: https://ec343ba38039.ngrok.io/hooks/github-build-webhook
            headers: '{"repository": "pilgrim2go/busybox"}'
            body: '{"event": "deployment", "repository": "pilgrim2go/busybox"}'        
